---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-south1-docker.pkg.dev/cicddemo-381608/cicddocker/cicd-demo
      PROJECT_ID: cicddemo-381608
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ vars.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: false

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-        
        echo "${{ vars.SERVICE_ACCOUNT_KEY }}" > KEY_FILE.json
        gcloud auth activate-service-account github-actions@cicddemo-381608.iam.gserviceaccount.com --key-file=KEY_FILE.json
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin http://asia-south1-docker.pkg.dev

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker push $IMAGE_NAME:latest
        